version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      DOCKER_ENV: "true" 
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    command: ["./taskmanager"]

volumes:
  pgdata:
